In [3]:
# with open('./drive/MyDrive/ReadME.md','w') as f:
#   data = f.write('리드미')
#   print('ㅇㅋ')

ㅇㅋ


# 넘파이(Numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 원소의 자료형

## 1차원과 속성들

In [12]:
import numpy as np
narry = np.array(range(5))
print(narry)
print(type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[4])
print(narry[2:4])

[0 1 2 3 4]
<class 'numpy.ndarray'>
1
(5,)
5
4
[2 3]


In [16]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b']) # 전부 다 문자 처리
narr3 = np.array([1,2,3,4],dtype = 'str')
print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [55]:
narr4 = np.zeros(10, dtype = 'int64')
narr5 = np.full((3,3),3)
narr6 = np.ones((2,2))
narr7 = np.full((2,2), 'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5, endpoint=False)
narr10 = np.arange(0,100,20)
print(narr4, type(narr4))
print(narr5, type(narr5))
print(narr6, type(narr6))
print(narr7, type(narr7))
print(narr8, type(narr8))
print(narr9, type(narr9))
print(narr10, type(narr10))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>
[['number' 'number']
 ['number' 'number']] <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
[ 0. 20. 40. 60. 80.] <class 'numpy.ndarray'>
[ 0 20 40 60 80] <class 'numpy.ndarray'>


# 2차원 배열

In [26]:
arr1 = np.zeros((2,2), dtype = 'int64')
print(arr1)

[[0 0]
 [0 0]]


In [33]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(list(range(2,10)))
print(range(2,10))
print(np.arange(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]
range(2, 10)
[2 3 4 5 6 7 8 9]


In [39]:
arr3 = np.arange(1,11).reshape(2,5)
arr4 = np.arange(1,11).reshape(5,2)

print(arr3)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [40]:
arr5 = np.arange(1,28).reshape(3,3,3)
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [52]:
ex1 = np.arange(1,22).reshape(3,7)
ex2 = np.arange(1,8).reshape(7,1)
ex3 = np.arange(1,11).reshape(5,2)
ex4 = np.arange(1,13).reshape(4,3,1)
print(ex1)
print("=" * 20)
print(ex2)
print("=" * 20)
print(ex3)
print("=" * 20)
print(ex4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [65]:
print(ex1[0:3, 3:7])

[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]


In [66]:
for e in ex1:
  print(e[3:7])

[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [74]:
print(ex1[ex1 > 14])

[15 16 17 18 19 20 21]


In [75]:
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print(np1 + np2)
print(np1 - np2)
print(np1 * np2)
print(np1 / np2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [78]:
np3 = np2 + 10
print(np3)

[16 17 18 19 20]


In [84]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
print(br1)
print(br1 + 3)
print(br1 * 2)
print(br1 + br2)
print(br1 * br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [88]:
print(br1.reshape(9))
print(br1.flatten())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [11]:
import numpy as np
x = np.random.randint(1,100,size = (10,5))
x

array([[ 2, 19, 33, 75, 72],
       [25, 45, 46, 97, 41],
       [71, 29, 29, 13, 50],
       [71, 24, 29, 10, 57],
       [18, 12, 21,  2, 65],
       [72, 49, 42, 22, 20],
       [94, 93, 58,  1, 58],
       [38, 80, 28,  6, 52],
       [95, 33, 36, 74, 28],
       [ 9, 65, 98, 58, 41]], dtype=int32)

In [13]:
print(f"평균 : {np.mean(x)}, 표준편차 : {np.std(x)}, 최대 : {x.max()}, 최소 : {x.min()}")

평균 : 44.12, 표준편차 : 27.410684048377924, 최대 : 98, 최소 : 1


In [15]:
print(len(x.flatten()))

50


In [18]:
y = np.array([0,1,2,0,3,4,5,6,0,7,8,9,0,3,5,4,0])
print(len(y))
print(np.count_nonzero(y))

17
12
