In [3]:
# with open('./drive/MyDrive/ReadME.md','w') as f:
#   data = f.write('리드미')
#   print('ㅇㅋ')

ㅇㅋ


# 넘파이(Numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 원소의 자료형

## 1차원과 속성들

In [12]:
import numpy as np
narry = np.array(range(5))
print(narry)
print(type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[4])
print(narry[2:4])

[0 1 2 3 4]
<class 'numpy.ndarray'>
1
(5,)
5
4
[2 3]


In [16]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b']) # 전부 다 문자 처리
narr3 = np.array([1,2,3,4],dtype = 'str')
print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [55]:
narr4 = np.zeros(10, dtype = 'int64')
narr5 = np.full((3,3),3)
narr6 = np.ones((2,2))
narr7 = np.full((2,2), 'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5, endpoint=False)
narr10 = np.arange(0,100,20)
print(narr4, type(narr4))
print(narr5, type(narr5))
print(narr6, type(narr6))
print(narr7, type(narr7))
print(narr8, type(narr8))
print(narr9, type(narr9))
print(narr10, type(narr10))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>
[['number' 'number']
 ['number' 'number']] <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
[ 0. 20. 40. 60. 80.] <class 'numpy.ndarray'>
[ 0 20 40 60 80] <class 'numpy.ndarray'>


# 2차원 배열

In [26]:
arr1 = np.zeros((2,2), dtype = 'int64')
print(arr1)

[[0 0]
 [0 0]]


In [33]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(list(range(2,10)))
print(range(2,10))
print(np.arange(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]
range(2, 10)
[2 3 4 5 6 7 8 9]


In [39]:
arr3 = np.arange(1,11).reshape(2,5)
arr4 = np.arange(1,11).reshape(5,2)

print(arr3)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [40]:
arr5 = np.arange(1,28).reshape(3,3,3)
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [52]:
ex1 = np.arange(1,22).reshape(3,7)
ex2 = np.arange(1,8).reshape(7,1)
ex3 = np.arange(1,11).reshape(5,2)
ex4 = np.arange(1,13).reshape(4,3,1)
print(ex1)
print("=" * 20)
print(ex2)
print("=" * 20)
print(ex3)
print("=" * 20)
print(ex4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [65]:
print(ex1[0:3, 3:7])

[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]


In [66]:
for e in ex1:
  print(e[3:7])

[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [74]:
print(ex1[ex1 > 14])

[15 16 17 18 19 20 21]


In [75]:
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print(np1 + np2)
print(np1 - np2)
print(np1 * np2)
print(np1 / np2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [78]:
np3 = np2 + 10
print(np3)

[16 17 18 19 20]


In [84]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
print(br1)
print(br1 + 3)
print(br1 * 2)
print(br1 + br2)
print(br1 * br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [88]:
print(br1.reshape(9))
print(br1.flatten())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [11]:
import numpy as np
x = np.random.randint(1,100,size = (10,5))
x

array([[ 2, 19, 33, 75, 72],
       [25, 45, 46, 97, 41],
       [71, 29, 29, 13, 50],
       [71, 24, 29, 10, 57],
       [18, 12, 21,  2, 65],
       [72, 49, 42, 22, 20],
       [94, 93, 58,  1, 58],
       [38, 80, 28,  6, 52],
       [95, 33, 36, 74, 28],
       [ 9, 65, 98, 58, 41]], dtype=int32)

In [13]:
print(f"평균 : {np.mean(x)}, 표준편차 : {np.std(x)}, 최대 : {x.max()}, 최소 : {x.min()}")

평균 : 44.12, 표준편차 : 27.410684048377924, 최대 : 98, 최소 : 1


In [15]:
print(len(x.flatten()))

50


In [18]:
y = np.array([0,1,2,0,3,4,5,6,0,7,8,9,0,3,5,4,0])
print(len(y))
print(np.count_nonzero(y))

17
12


# 판다스

- 시리즈
- 데이터프레임

In [6]:
import pandas as pd
import numpy as np

In [11]:
data1 = np.arange(1,11)
print(data1)
data2 = pd.Series(data1)
print(data2, type(data2), data2.index, data2.values, data2.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=10, step=1) [ 1  2  3  4  5  6  7  8  9 10] int64


In [12]:
data3 = pd.Series([1,2,3,4,5,6,7], dtype="float")
print(data3)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
dtype: float64


In [13]:
data3 = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [7]:
population_dict = {
    "Korea" : 5182,
    "Japan" : 12622,
    "China" : 141178,
    "USA" : 32676
}

country = pd.Series(population_dict)
population_dict.keys()
population_dict.values()
population_dict.items()
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
print(country.loc["Japan"])
print(country.iloc[1])

Korea      5182
Japan     12622
China    141178
USA       32676
dtype: int64 Index(['Korea', 'Japan', 'China', 'USA'], dtype='object') [  5182  12622 141178  32676]
1 (4,) 4
12622
12622


In [8]:
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index = ['a','b','c'], columns = ['A','B','C'])
df1

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [9]:
print("인구수 시리즈 데이터:")
population_dict = {
    "Korea" : 5182,
    "Japan" : 12622,
    "China" : 141178,
    "USA" : 32676
}
population = pd.Series(population_dict)
print(population)

print("GDP 시리즈 데이터:")
GDP_dict = {
    "Korea" : 169320000,
    "Japan" : 516700000,
    "China" : 140925000,
    "USA" : 2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print("=" * 20)
country = pd.DataFrame({'population':population, 'GDP':GDP})
print(country)
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)
country.index.name = "Country"
country.columns.name = "Info"
country

인구수 시리즈 데이터:
Korea      5182
Japan     12622
China    141178
USA       32676
dtype: int64
GDP 시리즈 데이터:
Korea     169320000
Japan     516700000
China     140925000
USA      2041280000
dtype: int64
       population         GDP
Korea        5182   169320000
Japan       12622   516700000
China      141178   140925000
USA         32676  2041280000
Index(['Korea', 'Japan', 'China', 'USA'], dtype='object') Index(['population', 'GDP'], dtype='object')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32676 2041280000]] (4, 2) 8 2


Info     population         GDP
Country                        
Korea          5182   169320000
Japan         12622   516700000
China        141178   140925000
USA           32676  2041280000

In [10]:
country.iloc[0],country.loc['Korea']

(Info
 population         5182
 GDP           169320000
 Name: Korea, dtype: int64,
 Info
 population         5182
 GDP           169320000
 Name: Korea, dtype: int64)

In [11]:
print(country.loc['Korea':'China','population'])

Country
Korea      5182
Japan     12622
China    141178
Name: population, dtype: int64


In [12]:
country.iloc[0:2,:1]

Info     population
Country            
Korea          5182
Japan         12622

In [13]:
country.iloc[1:4,1:2]

Info            GDP
Country            
Japan     516700000
China     140925000
USA      2041280000

In [14]:
country.iloc[1:3]

Info     population        GDP
Country                       
Japan         12622  516700000
China        141178  140925000

In [15]:
country['test'] = [1,2,3,4]
country = country.drop('test',axis = 1)
country['gdp_per'] = country['GDP'] / country['population']
country

Info     population         GDP       gdp_per
Country                                      
Korea          5182   169320000  32674.642995
Japan         12622   516700000  40936.460149
China        141178   140925000    998.207936
USA           32676  2041280000  62470.314604

In [28]:
country.loc['India'] = [142222, 150505000, 121]
country.loc['India', 'gdp_per'] = country.loc['India', 'GDP'] / country.loc['India', 'population']
country

Info     population           GDP       gdp_per
Country                                        
Korea        5182.0  1.693200e+08  32674.642995
Japan       12622.0  5.167000e+08  40936.460149
China      141178.0  1.409250e+08    998.207936
USA         32676.0  2.041280e+09  62470.314604
India      142222.0  1.505050e+08   1058.239935

In [29]:
africa = pd.Series( data = [123456,777777], index = ['population', 'GDP'])
country.loc['Africa'] = africa

In [30]:
country.loc['Africa','gdp_per'] = country.loc['Africa','GDP'] / country.loc['Africa','population']
country

Info     population           GDP       gdp_per
Country                                        
Korea        5182.0  1.693200e+08  32674.642995
Japan       12622.0  5.167000e+08  40936.460149
China      141178.0  1.409250e+08    998.207936
USA         32676.0  2.041280e+09  62470.314604
India      142222.0  1.505050e+08   1058.239935
Africa     123456.0  7.777770e+05      6.300034

In [31]:
country.isnull().sum()

Info
population    0
GDP           0
gdp_per       0
dtype: int64

In [32]:
country = country.drop('Africa', axis=0)
country

Info     population           GDP       gdp_per
Country                                        
Korea        5182.0  1.693200e+08  32674.642995
Japan       12622.0  5.167000e+08  40936.460149
China      141178.0  1.409250e+08    998.207936
USA         32676.0  2.041280e+09  62470.314604
India      142222.0  1.505050e+08   1058.239935

In [34]:
country[country['population'] > 140000]

Info     population          GDP      gdp_per
Country                                      
China      141178.0  140925000.0   998.207936
India      142222.0  150505000.0  1058.239935

In [54]:
country[(country['population'] > 10000) & (country['population'] < 140000)].loc[:,:'population']

Info     population
Country            
Japan       12622.0
USA         32676.0

In [107]:
name = {
    0 : "홍길동",
    1 : "박철수",
    2 : "김영희",
}
a = pd.Series(name)
df = pd.DataFrame({"이름":a})
국어 = [80,60,70]
수학 = [70,70,90]
영어 = [80,80,80]
df["국어"] = 국어
df["수학"] = 수학
df["영어"] = 영어
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [108]:
df.iloc[1:2,0:3]

이름  국어  수학
1  박철수  60  70

In [109]:
df[df["수학"] >= 70]

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [110]:
df["평균"] = (df["국어"] + df["수학"] + df["영어"]) / 3
df

이름  국어  수학  영어         평균
0  홍길동  80  70  80  76.666667
1  박철수  60  70  80  70.000000
2  김영희  70  90  80  80.000000

In [92]:
data_C = pd.Series(index = ["이름", "국어", "수학", "영어"], data = ['최자바', 55, 95, 70])
df.loc[3] = data_C
df

이름  국어  수학  영어         평균
0  홍길동  80  70  80  76.666667
1  박철수  60  70  80  70.000000
2  김영희  70  90  80  80.000000
3  최자바  55  95  70        NaN